Raise a ValueError when the xml answer has no order info.
Most likely cause is that the reporturl points to localhost,
which mollie.nl does not accept, because it cannot reach it.
Currently you would get an unclear error:
AttributeError: 'NoneType' object has no attribute 'find'